// Code generated by github.com/github.com/Filecoin-Titan/titan/node/config/cfgdocgen. DO NOT EDIT.

package config

type DocField struct {
	Name    string
	Type    string
	Comment string
}

var Doc = map[string][]DocField{
	"CandidateCfg": {
		{
			Name: "TCPSrvAddr",
			Type: "string",

			Comment: ``,
		},
		{
			Name: "IpfsAPIURL",
			Type: "string",

			Comment: ``,
		},
	},
	"EdgeCfg": {
		{
			Name: "ListenAddress",
			Type: "string",

			Comment: `host address and port the edge node api will listen on`,
		},
		{
			Name: "Timeout",
			Type: "string",

			Comment: `used when 'ListenAddress' is unspecified. must be a valid duration recognized by golang's time.ParseDuration function`,
		},
		{
			Name: "NodeID",
			Type: "string",

			Comment: `deivce id`,
		},
		{
			Name: "Secret",
			Type: "string",

			Comment: `used auth when connect to scheduler`,
		},
		{
			Name: "CarfileStorePath",
			Type: "string",

			Comment: `carfilestore path`,
		},
		{
			Name: "BandwidthUp",
			Type: "int64",

			Comment: `upload file bandwidth, unit is B/s`,
		},
		{
			Name: "BandwidthDown",
			Type: "int64",

			Comment: `download file bandwidth, unit is B/s`,
		},
		{
			Name: "Locator",
			Type: "bool",

			Comment: `if true, get scheduler url from locator`,
		},
		{
			Name: "InsecureSkipVerify",
			Type: "bool",

			Comment: `InsecureSkipVerify skip tls verify`,
		},
		{
			Name: "CertificatePath",
			Type: "string",

			Comment: `used for http3 server
be used if InsecureSkipVerify is true`,
		},
		{
			Name: "PrivateKeyPath",
			Type: "string",

			Comment: `used for http3 server
be used if InsecureSkipVerify is true`,
		},
		{
			Name: "CaCertificatePath",
			Type: "string",

			Comment: `self sign certificate, use for client`,
		},
		{
			Name: "FetchBlockTimeout",
			Type: "int",

			Comment: `FetchTimeout get block timeout`,
		},
		{
			Name: "FetchBlockRetry",
			Type: "int",

			Comment: `FetchBlockFailedRetry retry when get block failed`,
		},
	},
	"LocatorCfg": {
		{
			Name: "ListenAddress",
			Type: "string",

			Comment: `host address and port the edge node api will listen on`,
		},
		{
			Name: "Timeout",
			Type: "string",

			Comment: `used when 'ListenAddress' is unspecified. must be a valid duration recognized by golang's time.ParseDuration function`,
		},
		{
			Name: "GeoDBPath",
			Type: "string",

			Comment: `geodb path`,
		},
		{
			Name: "DatabaseAddress",
			Type: "string",

			Comment: `mysql db address`,
		},
		{
			Name: "UUID",
			Type: "string",

			Comment: `uuid`,
		},
		{
			Name: "InsecureSkipVerify",
			Type: "bool",

			Comment: `InsecureSkipVerify skip tls verify`,
		},
		{
			Name: "CertificatePath",
			Type: "string",

			Comment: `used for http3 server
be used if InsecureSkipVerify is true`,
		},
		{
			Name: "PrivateKeyPath",
			Type: "string",

			Comment: `used for http3 server
be used if InsecureSkipVerify is true`,
		},
		{
			Name: "CaCertificatePath",
			Type: "string",

			Comment: `self sign certificate, use for client`,
		},
	},
	"SchedulerCfg": {
		{
			Name: "ExternalAddress",
			Type: "string",

			Comment: `host external address and port`,
		},
		{
			Name: "ListenAddress",
			Type: "string",

			Comment: `host address and port the edge node api will listen on`,
		},
		{
			Name: "DatabaseAddress",
			Type: "string",

			Comment: `database address`,
		},
		{
			Name: "AreaID",
			Type: "string",

			Comment: `area id`,
		},
		{
			Name: "InsecureSkipVerify",
			Type: "bool",

			Comment: `InsecureSkipVerify skip tls verify`,
		},
		{
			Name: "CertificatePath",
			Type: "string",

			Comment: `used for http3 server
be used if InsecureSkipVerify is true`,
		},
		{
			Name: "PrivateKeyPath",
			Type: "string",

			Comment: `used for http3 server
be used if InsecureSkipVerify is true`,
		},
		{
			Name: "CaCertificatePath",
			Type: "string",

			Comment: `self sign certificate, use for client`,
		},
		{
			Name: "SchedulerServer1",
			Type: "string",

			Comment: `test nat type`,
		},
		{
			Name: "SchedulerServer2",
			Type: "string",

			Comment: `test nat type`,
		},
		{
			Name: "EnableValidate",
			Type: "bool",

			Comment: `config to enabled node validation, default: true`,
		},
		{
			Name: "EtcdAddresses",
			Type: "[]string",

			Comment: `etcd server addresses`,
		},
		{
			Name: "CandidateReplicaCachesCount",
			Type: "int",

			Comment: `Cache to the number of candidate nodes (does not contain 'seedCacheCount')`,
		},
	},
}
